### DISCUSSION TITLE
Building Your Own Independent SMS Gateway

### DISCUSSION THREAD

**Discussion by powerranger29** [capcom6/android-sms-gateway#71] [General]
Or at least tunnel the localhosted server somehow? I use 4g sim card internet with dynamic IP address and cannot access my local server from outside. Any solutions?

**Comment by powerranger29** [comment]
@capcom6 Also, if nothing else, would adding static ip with mobile internet provider solve that issue with local server?

**Comment by capcom6** [comment]
Hello!

Currently, the project doesn't natively support private servers. For now, you can use the provided public cloud server `sms.capcom.me` as outlined in our [Getting Started guide](https://sms.capcom.me/getting-started/#cloud-server).

If you're looking to connect to a local server over a connection with a dynamic IP, one workaround might be to set up a VPN from your device to a server that has a static public IP, along with the necessary routing configurations. However, instructions for setting up such a system are beyond the scope of this project.

The more complex route involves running your own server instance on a VPS (Virtual Private Server) or a similar service with a public IP. While the server component of the project isn't open-source-ready, there is a Docker image available, albeit without documentation at the moment. You'd also need to rebuild the Android app with your server address and updated Firebase credentials. If you're leaning towards this option, I will need some time to prepare and provide you with the necessary documentation for the server part.

Regarding your comment about a static IP: yes, having a static IP with your mobile internet provider could potentially resolve the issue with accessing your local server externally. However, that approach may have additional cost implications and would still require some network configuration.

I hope this clarifies your options. Let me know which path seems most suitable for you, and I'll do my best to assist you further.

**Comment by powerranger29** [comment]
for starters, id like to go with a dynamic ip (i have an option with my provider) Can you please guide me what network configuration should be done here like you mentioned?

I tried with the VPN before but could not manage it out of the box. VPN was active on my phone (through vpn app, not android vpn settings) but when trying to run sms gateway app locally it crashed (like it does when trying to run local server through my mobile internet). Any suggestion here maybe?

In the future it would be awesome if you could also open source the server component / add option to add custom server inside app.

**Comment by capcom6** [comment]
Actually, if you're considering using a dynamic IP, the most straightforward solution remains the public cloud server I previously mentioned. However, if you're referring to a `static IP` in your first sentence, then you should be able to see an external address for connection in the `Local server` section on the main app screen. You can try connecting to this address from another device. If that doesn't work, it would be a good idea to check with your provider to see which ports they allow for incoming connections to your IP. But see the last paragraph about crash.

Regarding the VPN issue, to successfully connect through a VPN, you'd typically need control over a server where you could adjust routing settings. Some VPN apps and services might offer such functionality, but I'm not aware of any specific ones to recommend at this time.

As for the app crash, I've managed to reproduce the issue and am planning to address it in an upcoming update. I will keep you posted and provide feedback as soon as the new version is available.

Thanks for your report.

**Comment by capcom6** [comment]
Hello!

I've released an update that should fix the crash on startup. Please download and try out version [v1.2.3](https://github.com/capcom6/android-sms-gateway/releases/tag/v1.2.3) and let me know how it goes.

**Comment by hacen-ai** [comment]
@capcom6 +1 for private cloud, I have my own vps and it will be realy cool if you can provide any documentation on how to edit the app so I can use it with my own cloud.BTW great work here thank you for make in it public for us, many thanks

**Comment by capcom6** [comment]
Hello!

Thanks for your feedback. I've started writing instructions for running your own private server for the app, but I found that the current version of the server is not quite suitable for private use.

Firstly, there are some not-so-clear steps:

1. Registration in the Firebase console and setting up Cloud Messaging on both the backend and the mobile app.
2. Rebuilding the Android app with source code changes.

And second, but more importantly, the current version of the backend is designed for public use. There are some publicly available endpoints that are inappropriate for private use. For example, anyone who knows your server address can register the app on the server.

While I will still publish the high-level instruction in a few days, please note that running this version of the server is not recommended for private use due to these challenges.

However, for the future, I plan to add one more mode to the application, in addition to "Local" and "Cloud" - "Private". For this mode, I'll be developing a simple server API-compatible with the Cloud mode, but for Push notifications, the Private server will leverage the Cloud server. Push notifications won't contain any information about the message (text or phones) for now, minimizing privacy impact. As for the mobile app, you'll set your own private server address in Private mode along with some credentials, so the mobile app will communicate only with your private server.

With this architecture, there's no need to rebuild the mobile app or register your own project in Firebase. Just start a minimal backend on your side and activate Private mode in the mobile app.

I'd appreciate any opinions about my architectural idea.

PS: I'll be releasing end-to-end encryption support for the app soon. This feature will allow you to encrypt messages before sending them via API, and they will only be decrypted in the mobile app. So if you're concerned about accessing message text or phone numbers on the backend side, this feature will address those concerns.

Thanks!

**Comment by capcom6** [comment]
Here is the quick start guide for deploying your own backend for the app.

## Before You Start

At the time of writing this document, the backend is not optimized for use as a private server. It contains public endpoints, and therefore, anyone who knows the server address can connect a mobile app to it and use the API.

Please note that this is a simplified instruction that does not provide detailed security settings, such as firewall configuration and HTTPS setup. It is the user's responsibility to implement these security measures.

**Use at your own risk.**

## Prerequisites

1. Android Studio with the Android SDK.
2. A Google Firebase account and a project with active Cloud Messaging.
3. A MySQL or MariaDB database.
4. A VPS with a public IP address.
5. A reverse proxy like Nginx or Traefik with HTTPS support.

## Server

1. Generate a Firebase service account private key.
2. Create a config file in YAML. Some variables can be overridden with environment variables. Example `config.yml`:
```yaml
http:
  listen: ":3000"   # HTTP__LISTEN
database:
  dialect: "mysql"  # DATABASE__DIALECT
  host: "localhost" # DATABASE__HOST
  port: 3306        # DATABASE__PORT
  user: "sms"       # DATABASE__USER
  password: "sms"   # DATABASE__PASSWORD
  database: "sms"   # DATABASE__DATABASE
  timezone: "UTC"   # DATABASE__TIMEZONE
fcm:
  credentials_json:  >
    {
    ...
    }
tasks:
  hashing:
    interval_seconds: 900
```
3. Create a `docker-compose.yaml` file like this:
```yaml
version: '3'
services:
  backend:
    image: capcom6/sms-gateway
    environment:
      - CONFIG_PATH=config.yml
      - HTTP__LISTEN=0.0.0.0:3000
      - DATABASE__HOST=db
      - DATABASE__PORT=3306
      - DATABASE__USER=sms
      - DATABASE__PASSWORD=sms
      - DATABASE__DATABASE=sms
    ports:
      - "3000:3000"
    volumes:
      - ./config.yml:/app/config.yml:ro
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sms
      - MYSQL_USER=sms
      - MYSQL_PASSWORD=sms
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-proot",
          "-h",
          "127.0.0.1"
        ]
      timeout: 5s
      retries: 10

volumes:
  mariadb-data:
```
4. Run `docker-compose up -d`.
5. Configure the reverse proxy to pass traffic to your server.

## Client

To build a version of the Android application that will communicate with your own server, follow these steps:

1. Clone the repository and open it in Android Studio.
2. Open `app/src/main/java/me/capcom/smsgateway/modules/gateway/GatewayApi.kt` and change the `BASE_URL` constant value to your server's URL.
3. Change the `applicationId` in `app/build.gradle` to a new value.
4. Follow the instructions from https://firebase.google.com/docs/android/setup to register your application and generate the `google-services.json` file.
5. Build and run the application.

**Reply by umerHasan** [reply]
Hi I am using firebase credentials but it is saying there is no project ID. The json has project_id in it. I don't know how you are parsing the credentials but it does not seem to work. I have tried everything. Can you please give me a sample firebase config just to show the structure of the json object or guide me about it? There is no mention of credentials structure in the documentation.

**Reply by capcom6** [reply]
@umerHasan, hello!

The credentials are passed directly to Firebase without any modification. Please ensure that your JSON is correctly formatted and indented inside YAML. Below is an example of the structure of the Firebase config JSON object.

```yaml
fcm:
  credentials_json: >
    {
      "type": "service_account",
      "project_id": "your-project-id",
      "private_key_id": "your-private-key-id",
      "private_key": "your-private-key",
      "client_email": "your-client-email",
      "client_id": "your-client-id",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "your-client-x509-cert-url"
    }
```
