### ISSUE TITLE
401 Unauthorized on Private Server

### ISSUE THREAD

**Issue by yatesdr** [capcom6/android-sms-gateway#228]
I'm attempting to run it "cloud" private server using compose, and can't seem to get a message out.   Consistently get a 401 / unauthorized message when using postman or curl against the top level domain.   It works fine when using the local server, but using the cloud server is rejected for an unknown reason.   Logs not much help, but they do log the attempt and response of 401 unauthorized.

1). For Post-man, does it use basic auth with username and password?  Or some other type of token?
2). For curl, not sure why it's failing.

curl attempt:
```
curl -X POST -u USERNAME_FROM_APP:PASSWORD_FROM_APP -H "Content-Type: application/json" -d '{ "message": "Hello, doctors!", "phoneNumbers": ["+16165555555"] }' https://sms.my_host.com/api/mobile/v1/message
```

Architecture:

Back-end and MariaDB are running in compose, with a separate NGINX proxy doing the SSL termination and proxy pass to this instance.

docker-compose.yaml:
```
name: smsgate
services:
  smsgate:
    image: ghcr.io/android-sms-gateway/server:latest
    ports:
     - "3000:3000"
    environment:
      - CONFIG_PATH=config.yml
      - DATABASE__PASSWORD=${MYSQL_PASSWORD}
      - GATEWAY__PRIVATE_TOKEN=${GATEWAY_PRIVATE_TOKEN}
    configs:
      - source: config-yml
        target: /app/config.yml
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=sms
      - MYSQL_USER=sms
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
     - mariadb-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

configs:        
  config-yml:                                                             
    content: |         
      gateway:     
        mode: private                             
      http:               
        listen: 0.0.0.0:3000
      database:                         
        host: mariadb
        port: 3306                
        user: sms
        password: ${MYSQL_PASSWORD}
        database: sms                                                     
      fcm:                  
        credentials_json: "{}"
        timeout_seconds: 1
        debounce_seconds: 5
      tasks:     
        hashing:                   
          interval_seconds: 900
              
volumes:                      
  mariadb-data:
```

.env file with passwords removed:
```
MYSQL_ROOT_PASSWORD=<long random password>
MYSQL_PASSWORD=<random password>
GATEWAY_PRIVATE_TOKEN=<private token>
```

nginx.conf snippet:
```
server {             
  server_name sms.my_host.com;     
  location / {                       
        proxy_pass http://<internal-ip>:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-Ip $remote_addr;
  }                            
                                                                 
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/sms.my_host.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/sms.my_host.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
                                
}
```
